bot:
  account:  
  password: 
  commandPrefix: ""     # bot触发命令的前缀，默认为单斜杠 /
  onDisconnected: "" # 设置掉线时处理方式，exit为退出，不填或者其他值为尝试重连
  onJoinGroup:
    rename: "7号机"     # BOT进群后自动改名，默认改名为“【bot】”，如果留空则不自动改名

# 请注意，bot将使用您b站帐号的以下功能，建议使用新注册的小号：
# 关注用户 / 取消关注用户 / 查看关注列表
# 目前支持填cookie和账号两种方式 （选择任意一种方式即可，推荐使用账号密码）
# 若使用账号
    # 直接填入账号密码
# 若使用cookie
    # b站登陆后的cookie字段，从cookie中找到这两个填进去
    # 警告：
    # SESSDATA和bili_jct等价于您的帐号凭证
    # 请绝对不要透露给他人，更不能上传至Github等公开平台
    # 否则将导致您的帐号被盗
# 请注意，订阅一个账号后，此处使用的b站账号将自动关注该账号
bilibili:
  SESSDATA: "4a550026%2C1682744354%2Ccceae%2Aa2"
  bili_jct: "c7785ccc02abcfc3a5e6dbc58c83fd2e"
  account:  # 你的b站账号 （目前不可用）
  password: # 你的b站密码 （目前不可用）
  interval: 25s # 直播状态和动态检测间隔，过快可能导致ip被暂时封禁
  imageMergeMode: "auto" # 设置图片合并模式，支持 "auto" / "only9" / "off"
                         # auto 为默认策略，存在比较刷屏的图片时会合并
                         # only9 表示仅当恰好是9张图片的时候合并
                         # off 表示不合并
  hiddenSub: false    # 是否使用悄悄关注，默认不使用
  unsub: false        # 是否自动取消关注，默认不取消，如果您的b站账号有多个bot同时使用，取消可能导致推送丢失
  minFollowerCap: 0        # 设置订阅的b站用户需要满足至少有多少个粉丝，默认为0，设为-1表示无限制
  disableSub: false        # 禁止ddbot去b站关注帐号，这意味着只能订阅帐号已关注的用户，或者在b站手动关注
  onlyOnlineNotify: false  # 是否不推送Bot离线期间的动态和直播，默认为false表示需要推送，设置为true表示不推送

localPool: # 图片功能，使用本地图库
  imageDir: # 本地路径

loliconPool: # 图片功能，使用api.lolicon.app图库
  apikey:    # 由于该图库更新，此字段不再需要了，留空即可
  cacheMin: 10
  cacheMax: 50
  proxy:

pyProxyPool: # 代理池配置，py代理池 https://github.com/jhao104/proxy_pool
  host: http://127.0.0.1:5010

localProxyPool: # 代理池配置，固定代理
  oversea: # 可翻墙的代理，用于访问YTB或pixiv
    - 127.0.0.1:8888
  mainland: # 不可翻墙的代理，用于直连国内网站
    - 127.0.0.1:8888

# 加入 twitcasting 部分即启用 tc 订阅功能  
# 参阅 https://apiv2-doc.twitcasting.tv/#registration
# 你需要到 https://twitcasting.tv/developer.php 新增一个 App
# 填入所需资料后就可以获取 clientId 和 clientSecret
# 详细: https://www.codenong.com/7d930656a7499340f14a/
twitcasting:
  clientId: abc
  clientSecret: xyz
  # 为防止风控，可选择性广播以下元素
  broadcaster:
    title: false # 标题 (有风控机会)
    created: true # 开播时间
    image: false # 直播封面 (墙内无法获取TC直播封面，建议有代理才开启
  # 自定义名称显示，日文字太多很大机会风控
  # 例如 "(如何显示) 正在直播""
  nameStrategy: "name" # 如何显示名称, name= 显示用户名称, userid= 显示用户ID, both= 显示 "用户名称 (用户ID)"

concern:
  emitInterval: 5s # 订阅的刷新频率，5s表示每5秒刷新一个ID，过快可能导致ip被暂时封禁

imagePool:
  type: "off" # localPool / loliconPool

proxy:
  type: "off" # localProxyPool/ pyProxyPool

debug: # debug模式，只有以下群或qq号可以触发命令
  group:
    - 0
  uin:
    - 0

message-marker: # 是否禁用自动已读功能，true为禁用，false为不禁用，默认为不禁用
  disable: false

qq-logs: # 是否启用在命令行内展示qq聊天内容，true为启用，false为禁用，默认为禁用
  enable: false

dispatch:
  largeNotifyLimit: 5 # 巨量推送的判定配置，默认为50，当大于这个配置时，将增大推送延迟保证账号稳定
notify:
  parallel: 1          # 增加推送消息的并发配置，默认为1以优先保证账号稳定，当出现推送堆积的时候可以尝试调高

template:       # 是否启用模板功能，true为启用，false为禁用，默认为禁用
  enable: true # 需要了解模板请看模板文档
  
autoreply: # 自定义命令自动回复，自定义命令通过模板发送消息，且不支持任何参数，需要同时启用模板功能
  group:   # 需要了解该功能请看模板文档
    command: [ "oo", "kk", "原神", "查成分", "查疫情","头像","百度"  ]
  private:
    command: [ ]

# 重定义命令前缀，优先级高于bot.commandPrefix
# 如果有多个，可填写多项，prefix支持留空，可搭配自定义命令使用
# 例如下面的配置为：<Q命令1> <命令2> </help>
customCommandPrefix:
  kk: ""
  oo: ""
  原神: ""
  查疫情: ""
  百度: ""
  list: ""



logLevel: info # 日志等级